Lab_1/lab_1/lab_1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myuser.urls')),
    path('Track/', include('track.urls')),
    path('Trainee/', include('trainee.urls')),
]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)


Lab_1/lab_1/myuser/urls.py
from django.urls import path
from .views import *
app_name = 'myuser'
urlpatterns = [
    path("Login/", Login, name='login'),
    path("Register/", Register, name='register'),
    path("Logout/", Logout, name='logout'),
]

Lab_1/lab_1/track/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', alltracks, name="alltracks"),
    path('Insert/', Insert, name="inserttrack"),
    path('Update/<int:id>/', Update, name='updatetrack'),
    path('Delete/<int:id>/', Delete, name='deletetrack')
]

Lab_1/lab_1/trainee/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', Alltrainee, name='alltrainees'),
    path('Insert/', Insert, name="insert_tr"),
    path('Update/<int:id>/', Update, name='update_tr'),
    path('Delete/<int:id>/', Delete, name='delete_tr')
]

Lab_1/lab_1/myuser/models.py
from django.db import models

# Create your models here.

Lab_1/lab_1/track/models.py
from django.db import models
from django.db.models import Count, Q
# Create your models here.

class Track(models.Model):
    id=models.AutoField(primary_key=True)
    name=models.CharField(max_length=100, null=False, unique=True)

    @classmethod
    def getalltracks(cls):
        return cls.objects.all()

    @classmethod
    def getalltracks_N_numtr(cls):
        return cls.objects.annotate(numberoftr=Count('trainee', filter=Q(trainee__status=True))).order_by('id')
    
    @classmethod
    def gettrackbyid(cls, id):
        return cls.objects.get(id=id)

Lab_1/lab_1/trainee/models.py
from django.db import models
from track.models import Track
# Create your models here.

class Trainee (models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=50, null=False)
    email = models.EmailField(max_length=100, unique=True, null=False)
    image = models.ImageField(upload_to='trainees/images/')
    status = models.BooleanField(default=True)
    trackid = models.ForeignKey(Track, on_delete= models.CASCADE)

    @classmethod
    def getalltrainees(cls):
        return cls.objects.all()

    @classmethod
    def gettraineebyid(cls, id):
        return cls.objects.get(id=id)

Lab_1/lab_1/myuser/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def Login(request):
    return render(request, 'myuser/login.html')

def Register(request):
    return render(request, 'myuser/register.html')

def Logout(request):
    return HttpResponse("<h1> Goodbye </h1>")

Lab_1/lab_1/track/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Track

# Create your views here.

def alltracks(request):
    context={}
    context['tracks'] = Track.getalltracks_N_numtr()
    return render(request, 'track/list.html', context)

def Insert(request):
    if request.method == 'POST':
        Track.objects.create(name=request.POST['track'])
        return redirect('alltracks')
    return render(request, 'track/insert.html')

def Update(request, id):
    track = Track.gettrackbyid(id)
    context = {'track':track} #Get current track

    # Check updates
    if request.method == 'POST':
        track.name = request.POST['track']
        track.save()
        return redirect('alltracks') 

    return render(request, 'track/update.html', context)

def Delete(request, id):
    Track.objects.filter(id=id).delete()
    return redirect('alltracks')


Lab_1/lab_1/trainee/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Trainee
from track.models import Track

# Create your views here.

def Alltrainee(request):
    context={}
    context['trainees'] = Trainee.getalltrainees().order_by('id')
    return render(request, 'trainee/list.html', context)

def Insert(request):
    if request.method == 'POST':
        Trainee.objects.create(name=request.POST['trName'],
                               email=request.POST['trEmail'], 
                               image=request.FILES.get('trImage'),
                               trackid=Track.gettrackbyid(request.POST['trtrack']))
        return redirect('alltrainees')
    
    context = {}
    context['tracks'] = Track.getalltracks()
    return render(request, 'trainee/insert.html', context)

def Update(request, id):
    trainee = Trainee.gettraineebyid(id)
    context = {'trainee':trainee}
    context['tracks'] = Track.getalltracks()

    if request.method == 'POST':
        trainee.name = request.POST['trName']
        trainee.email = request.POST['trEmail']
        trainee.trackid = Track.gettrackbyid(request.POST['trtrack']) # Get Object
        if request.FILES.get('trImage'):
            trainee.image = request.FILES['trImage']
        
        if request.POST.get('trstatus'):
            trainee.status = True
        else:
            trainee.status = False

        
        
        trainee.save()
        return redirect('alltrainees')
    
    return render(request, 'trainee/update.html', context)

def Delete(request, id):
    Trainee.objects.filter(id=id).update(status=False)
    return redirect('alltrainees')

Lab_1/lab_1/myuser/templates/myuser/login.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}
{% load static %}

{%block style %}
<link href="{% static 'css/style.css'%}" rel="stylesheet">
{% endblock %}

{% block content %}
<h1>Hello from Login</h1>

<a href="{% url 'myuser:logout'%}">Logout</a>

{% endblock %}

Lab_1/lab_1/myuser/templates/myuser/register.html
{% extends 'base.html' %}

{% block title %}Register{% endblock %}
{% load static %}

{%block style %}
<link href="{% static 'css/register.css'%}" rel="stylesheet">
{% endblock %}

{% block content %}
<form method="GET" action="..\templates\Thankyou.html">
    <table align="center">
        <tr>
            <th colspan="2">
                <h2>Registration Page</h2>
            </th>
        </tr>
        <tr>
            <td>
                <label for="fname" id="fname">First Name:</label>
            </td>
            <td>
                <input type="text" id="fname" name="fname" required>
            </td>
        </tr>
        <tr>
            <td>
                <label for="lname" id="lname">Last Name:</label>
            </td>
            <td>
                <input type="text" id="lname" name="lname" required>
            </td>
        </tr>
        <tr>
            <td>
                <label for="email" id="email">Email:</label>
            </td>
            <td>
                <input type="email" id="email" name="email" required>
            </td>
        </tr>
        <tr>
            <td>
                <label for="pass" id="pass">Password:</label>
            </td>
            <td>
                <input type="password" id="pass" name="pass" required>
            </td>
        </tr>
        <tr>
            <td>
                <label for="rpass" id="rpass">Repeat Password:</label>
            </td>
            <td>
                <input type="password" id="rpass" name="rpass" required>
            </td>
        </tr>
        <tr>
            <td>
                <label for="bdate" id="bdate">Birth Date:</label>
            </td>
            <td>
                <input type="date" id="bdate" name="bdate" required>
            </td>
        </tr>
        <tr>
            <td>
                <label for="pic" id="pic">User Picture:</label>
            </td>
            <td>
                <input type="file" id="pic" name="pic">
            </td>
        </tr>
        <tr>
            <td>
                <label for="gender" id="gender">Gender:</label>
            </td>
            <td>
                <input type="radio" name="gender" id="male">
                <label for="male">Male</label>
                <input type="radio" name="gender" id="female">
                <label for="female">Female</label><br>
            </td>
        </tr>
        <tr>
            <td>
                <label for="faculty" id="faculty">Faculty of:</label>
            </td>
            <td>
                <select name="faculty" id="faculty">
                    <option value="" disabled selected>-- select option --</option>
                    <option value="engineering">Engineering</option>
                    <option value="Medicine">Medicine</option>
                    <option value="Pharmacy">Pharmacy</option>
                    <option value="Dentistry">Dentistry</option>
                    <option value="Business">Business</option>
                </select>
            </td>
        </tr>
        <tr>
            <td style="vertical-align: top;">
                <label for="interests" id="interests">Interests:</label>
            </td>
            <td>
                <input type="checkbox" name="interests" id="programming">
                <label for="programming">Programming</label><br>

                <input type="checkbox" name="interests" id="swimming">
                <label for="swimming">Swimming</label><br>

                <input type="checkbox" name="interests" id="reading">
                <label for="reading">Reading</label><br>

                <input type="checkbox" name="interests" id="football">
                <label for="football">Football</label><br>
            </td>
        </tr>
        <tr>
            <td>About you:</td>
            <td>
                <textarea name="about" id="about"></textarea>
            </td>
        </tr>
        <tr>
            <td>I agreed to terms and condition</td>
            <td>
                <input type="checkbox" name="terms" id="terms" required>
            </td>
        </tr>
        <tr>
            <td colspan="2" align="center">
                <input type="submit" value="Register">
                <input type="reset" value="Reset">
                <a href="{% url 'myuser:login'%}" style="margin: 10px;">Login</a>
            </td>
        </tr>
    </table>
</form>
{% endblock %}

Lab_1/lab_1/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Base-Parent{% endblock %}</title>
    <link href="{% static 'css/style.css'%}" rel="stylesheet">
</head>

<body>
    <table width="100%" id="base">
        <tr>
            <td id="header">
                <a href="{% url 'alltracks'%}">Tracks</a>
                <a href="{% url 'alltrainees'%}">Trainees</a>
            </td>
        </tr>
        <tr>
            <td>
                {% block content %}
                Content
                {% endblock %}
            </td>
        </tr>
        <tr id="footer">
            <td>
                Copyrights &#169; are reserved to ITI
            </td>
        </tr>
    </table>
    <script src="{% static 'js/asd.js'%}"></script>
</body>

</html>

Lab_1/lab_1/track/templates/track/insert.html
{% extends 'base.html'%}

{% block title%}
    Insert Track
{% endblock %}

{% block content %}
<h1> Insert Track</h1>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <label for="track">Track Name:</label>
    <input type="text" id="track" name="track">
    <input type="submit" id="Insert Track">
</form>
{% endblock %}

Lab_1/lab_1/track/templates/track/list.html
{% extends 'base.html' %}

{% block title %}
tracks
{% endblock %}

{% block content %}
<a href="{% url 'inserttrack'%}">Insert Track</a>

<h1>All Tracks</h1>
<table width="100%" border="solid" style="border-collapse: collapse;">
  <tr>
    <th>ID</th>
    <th>Name</th>
    <th>Number of Trainees</th>
    <th>Action</th>
  </tr>
  {% for track in tracks %}
  <tr>
    <td>{{ track.id }}</td>
    <td>{{ track.name }}</td>
    <td>{{ track.numberoftr }}</td>
    <td>
      <div class="action">
        <a href="{% url 'updatetrack' track.id %}">Update</a>
        <a href="{% url 'deletetrack' track.id %}">Delete</a>
      </div>
    </td>
  </tr>
  {% endfor %}
</table>
{% endblock %}

Lab_1/lab_1/track/templates/track/update.html
{% extends 'base.html'%}

{% block title%}
    Update Track
{% endblock %}

{% block content %}
<h1> Update Track</h1>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <label for="track">Track Name:</label>
    <input type="text" id="track" name="track" value ="{{track.name}}">
    <input type="submit" id="Insert Track">
</form>
{% endblock %}

Lab_1/lab_1/trainee/templates/trainee/insert.html
{% extends 'base.html'%}

{% block title%}
    Insert Trainee
{% endblock %}

{% block content %}
<h1>Insert Trainee</h1>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <label for="trName">Name:</label>
    <input type="text" id="trName" name="trName">
    <br><br>
    <label for="trEmail">Email:</label>
    <input type="email" id="trEmail" name="trEmail">
    <br><br>
    <select id="trtrack" name="trtrack">
        {% for track in tracks %}
        <option value="{{track.id}}">{{track.name}}</option>
        {% endfor %}
    </select>
    <br><br>
    <label for="trImage">Image:</label>
    <input type="file" id="trImage" name="trImage">
    <br><br>
    <input type="submit" value="Insert Trainee">
</form>
{% endblock %}

Lab_1/lab_1/trainee/templates/trainee/list.html
{% extends 'base.html' %}

{% block title %}
Trainees
{% endblock %}

{% block content %}
<a href="{% url 'insert_tr' %}">New Trainee</a>
<h1>All Trainees</h1>
<table width="100%" border="1" style="border-collapse: collapse;">
  <tr>
    <th>ID</th>
    <th>Name</th>
    <th>Email</th>
    <th>Track</th>
    <th>Status</th>
    <th>Image</th>
    <th>Action</th>
  </tr>
  {% for trainee in trainees %}
  <tr>
    <td>{{ trainee.id }}</td>
    <td>{{ trainee.name }}</td>
    <td>{{ trainee.email }}</td>
    <td>{{ trainee.trackid.name }}</td>
    <td>{% if trainee.status %} Active {% else %} Inactive {% endif %}</td>
    <td>
      <img src="{{ trainee.image.url }}" width="100px" height="100px">
    </td>
    <td>
      <div class="action">
        <a href="{% url 'update_tr' trainee.id %}">Update</a>
        <a href="{% url 'delete_tr' trainee.id %}">Delete</a>
      </div>
    </td>
  </tr>
  {% endfor %}
</table>
{% endblock %}

Lab_1/lab_1/trainee/templates/trainee/update.html
{% extends 'base.html'%}

{% block title%}
    Insert Trainee
{% endblock %}

{% block content %}
<h1>Update Trainee</h1>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <label for="trName">Name:</label>
    <input type="text" id="trName" name="trName" value="{{trainee.name}}">
    <br><br>
    <label for="trEmail">Email:</label>
    <input type="email" id="trEmail" name="trEmail"  value="{{trainee.email}}">
    <br><br>
    <select id="trtrack" name="trtrack">
        {% for track in tracks %}
            {% if track.id == trainee.trackid.id %}
                <option value="{{track.id}}" selected>{{track.name}}</option>
            {% else %}
                <option value="{{track.id}}">{{track.name}}</option>
            {% endif %}
        {% endfor %}
    </select>
    <br><br>
    {% if block %}
    <label for="">Current Image:</label>
    <img src="{{ trainee.image.url }}" width="100px">
    <br><br>
    {% endif %}
    <label for="trImage">Image:</label>
    <input type="file" id="trImage" name="trImage">
    <br><br>
    <label for="trstatus">Status:</label>
    <input type="checkbox" id="trstatus" name="trstatus" {% if trainee.status %}checked{% endif %}>
    <br><br>
    <input type="submit" value="Update Trainee">
</form>
{% endblock %}